---
myria_repository_url: https://github.com/uwescience/myria.git
myria_path: '{{install_base_path}}/myria'
myria_branch: master
namenode_port: 8020
coordinator_port: 8001
worker_base_port: 9001
database_password: uwdb # TODO fix me :(
